# Generated by Django 5.2.5 on 2025-08-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Salary',
            new_name='salary',
        ),
    ]
