# Generated by Django 5.2.5 on 2025-08-18 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_alter_savedjob_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='Salary',
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save_job', to=settings.AUTH_USER_MODEL),
        ),
    ]
