# Generated by Django 5.2.5 on 2025-08-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Salary',
            new_name='salary',
        ),
    ]
